config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  root 'static_pages#home'
  get 'home' => 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home 
  end
  	
  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns the full title on per-page basis
	def full_title(page_title = '')
		base_title = "Save Haryana"
		if page_title.empty?
			base_title
		else 
			page_title + " | " + base_title
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

	def line_break(n)
		("<br/>" *n).html_safe
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <i>Save Haryana Campaign</i>
    by an <i>Educated JAT</i>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="Link to where the news would show up">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Save Haryana", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",  root_path %></li>
        <li><%= link_to "Help",  help_path %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>  
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %> 
<h1>About</h1>

<p>
  We are a bunch of tech entreprenuers who think every stupid decision can
  be reversed or fixed by Technology

  <%= line_break(3) %>


  Like Math can solve Mathematical problems. Getting together can fix any
  real life problem. 

  Why should you pay and help who suffer?


  <%= link_to image_tag("crying.png", alt: "Crying Women") %>

  Because you are Human and you only religion is Humanity. Agreed? 

  Imagine 1.252 Billion Indian population paying just One Rupee. We 1.252 population has the power to run our own fucking Govt.

  <%= line_break(3) %>

  This sitution looks even smaller :D
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>

<p>Contact 
<%= link_to 'Abhimanyu', 'https://www.twitter.com/iAbhimanyuAryan'
 for any person issues </p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  If you want any kind of help regarding donation you can contact our
  help team any where

  <div class="col-md-3 img-responsive small-size">
  <%= link_to image_tag("abhimanyu.png", alt: "Abhimanyu Aryan"), "https://www.facebook.com/iAbhimanyuAryan/" %> Abhimanyu Aryan

  <%= link_to image_tag("aditya.png", alt: "Aditya Gulia"),
  "https://www.facebook.com/-----------" %> Aditya Gulia
  </div>

</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Save Haryana Campaign</h1>

  <h2>This website is to help people who suffered in. We are <em>trying</em> to gather some amount to help poor people who lost there homes, shops in
  </h2>

  <%= link_to "Donate Now", 'http://www.funddreamsindia.com/campaign/a-helping-hand-to-rebuild-haryana/499/', class: "btn btn-lg btn-primary" %>

  <%= link_to "All Recieved Donations", signup_path , class: "btn btn-lg btn-success" %></a>

  </div>
  
  <%= link_to image_tag("cars1.png", alt: "Burnt show room"), '#' %>
  <p class="center">
  
  
  <%= line_break(3) %>
  
  <a href="">Haryana gathers donation</a> is a affort to help who lost
  something more than just hope. 
  
  <%= line_break(2) %>
  <%= link_to image_tag("powerhouse.png", alt: "Burnt cars"), '#' %>
  <%= line_break(2) %>

  All you need to do is <i>contact us</i> via telephone/email/Social Networking(Twitter/Facebook/Google Plus/Instagram any one of your choice). And submit your donation publicly to the list

  We will offer your donation to people who are suffering. 

  <%= line_break(2) %>
  <%= link_to image_tag("buses.png", alt: "Buses Burnt"), '#' %>

  <%= line_break(2) %>

  There are people who watch movies and clap on heroic actions. Well its your time to a hero. You wish to be hero? Donate any amount of money you feel like

  <%= line_break(2) %>
  <%= image_tag("bikes.png", alt: "Bikes Burnt") %>
  <%= line_break(1) %>

  If wish to donate anonymously, you can donate via Bitcoin. Just make a account on Coinsecure. And pay via Bitcoin on the string Below

  <%= line_break(3) %>

  We accept Bitcoin payments upto 1 crore. Thanks for being human. You are a great example of humanity
</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>